FROM node:22-alpine AS builder
RUN apk add --no-cache gcompat
WORKDIR /app
COPY package*.json ./
COPY .npmrc ./
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build -- --configuration development

FROM nginx:alpine
COPY --from=builder /app/dist/daf360-rh-frontend/browser /usr/share/nginx/html
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf
EXPOSE 4203
