import { Component, inject, input, output } from '@angular/core';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import {
  FormFieldComponent, MultiDatePickerComponent,
  SelectComponent, SelectOption, ToggleComponent,
} from '@khalilrebhiitec/daf360';

import { EmployeeProfile, ProfileUpdateDto } from '../models/profile.model';
import { ProfileFieldComponent } from './profile-field.component';
import { SectionCardComponent } from './section-card.component';
import { asNumber, fmtDate, fromDate, toDate } from './field-bridges';

/**
 * Emploi tab — two accent-bordered cards side by side, per
 * `design/profile-detail.html`: the contract facts, and the salary figures.
 *
 * Read mode uses the design's label ⟷ value rows; edit mode swaps in the lib
 * controls. The "Période d'essai" switch sits in the first card's header, as in
 * the design, and is only interactive while editing.
 */
@Component({
  selector: 'rh-employment-section',
  standalone: true,
  imports: [
    ProfileFieldComponent, SectionCardComponent, FormFieldComponent,
    MultiDatePickerComponent, SelectComponent, ToggleComponent, TranslatePipe,
  ],
  host: { class: 'block' },
  template: `
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2">

      <!-- ── Emploi & contrat ── -->
      <rh-section-card
        [title]="'PROFILES.SECTIONS.EMPLOYMENT' | translate" icon="description" tone="text-primary"
        accent="primary">
        <daf-toggle sectionAction
          [options]="{ label: ('PROFILES.FIELDS.ON_PROBATION' | translate), disabled: !editMode() }"
          [checked]="editMode() ? (editForm().isOnProbation ?? false) : profile().isOnProbation"
          (checkedChange)="patch.emit({ isOnProbation: $event })" />

        @if (!editMode()) {
          <!-- Exactly the four rows the design lists. Country moved to the badges,
               and the contract-end / onboarding / audit values sit in the tab's
               meta strip so this card stays the design's shape. -->
          <div class="flex flex-col">
            <rh-profile-field variant="row"
              [label]="'PROFILES.FIELDS.MATRICULE' | translate" [value]="profile().matricule" />
            <rh-profile-field variant="row"
              [label]="'PROFILES.FIELDS.HIRE_DATE' | translate" [value]="fmtDate(profile().hireDate)" />
            <rh-profile-field variant="row" valueClass="text-primary"
              [label]="'PROFILES.FIELDS.CONTRACT_TYPE' | translate" [value]="profile().contractType" />
            <rh-profile-field variant="row" [last]="true"
              [label]="'PROFILES.FIELDS.PROBATION_END' | translate" [value]="fmtDate(profile().probationEndDate)" />
          </div>
        } @else {
          <div class="flex flex-col gap-4">
            <!-- Matricule is generated by the backend — never editable. Contract end
                 reappears here because it *is* editable; hiding it in edit mode
                 would make the field unreachable. -->
            <rh-profile-field variant="row" [last]="true"
              [label]="'PROFILES.FIELDS.MATRICULE' | translate" [value]="profile().matricule" />
            <daf-multi-date-picker
              [config]="{ label: ('PROFILES.FIELDS.HIRE_DATE' | translate), selectionMode: 'single' }"
              [value]="toDate(editForm().hireDate)"
              (valueChange)="patch.emit({ hireDate: fromDate($event) })" />
            <daf-select [options]="contractTypeOptions()"
              [config]="{ label: ('PROFILES.FIELDS.CONTRACT_TYPE' | translate), searchable: true }"
              [selected]="editForm().contractType ? [editForm().contractType!] : []"
              (selectedChange)="patch.emit({ contractType: $event[0] })" />
            <daf-multi-date-picker
              [config]="{ label: ('PROFILES.FIELDS.CONTRACT_END' | translate), selectionMode: 'single' }"
              [value]="toDate(editForm().contractEndDate)"
              (valueChange)="patch.emit({ contractEndDate: fromDate($event) })" />
            <daf-multi-date-picker
              [config]="{ label: ('PROFILES.FIELDS.PROBATION_END' | translate), selectionMode: 'single' }"
              [value]="toDate(editForm().probationEndDate)"
              (valueChange)="patch.emit({ probationEndDate: fromDate($event) })" />
          </div>
        }
      </rh-section-card>

      <!-- ── Prétentions & rémunération ── -->
      <rh-section-card
        [title]="'PROFILES.SECTIONS.COMPENSATION' | translate" icon="payments" tone="text-tertiary"
        accent="tertiary">

        @if (!editMode()) {
          <div class="flex flex-col">
            <rh-profile-field variant="row"
              [label]="'PROFILES.FIELDS.SALARY_CANDIDATE' | translate" [value]="amount(profile().salaireNetCandidat)" />
            <rh-profile-field variant="row" valueClass="text-tertiary"
              [label]="'PROFILES.FIELDS.SALARY_RH' | translate" [value]="amount(profile().salaireNetRh)" />
            <!-- Currency and pay frequency are fixed: employee_profiles has no column
                 for either, so these are constants, not data. -->
            <rh-profile-field variant="row"
              [label]="'PROFILES.FIELDS.CURRENCY' | translate" [value]="CURRENCY" />
            <rh-profile-field variant="row" [last]="true"
              [label]="'PROFILES.FIELDS.PAY_FREQUENCY' | translate"
              [value]="'PROFILES.PAY_FREQUENCY.MONTHLY' | translate" />
          </div>
        } @else {
          <div class="flex flex-col gap-4">
            <daf-form-field
              [options]="{ label: ('PROFILES.FIELDS.SALARY_CANDIDATE_INPUT' | translate), type: 'number',
                           placeholder: ('PROFILES.PLACEHOLDERS.SALARY_CANDIDATE' | translate) }"
              [value]="editForm().salaireNetCandidat ?? null"
              (valueChange)="patch.emit({ salaireNetCandidat: asNumber($event) })" />
            <daf-form-field
              [options]="{ label: ('PROFILES.FIELDS.SALARY_RH_INPUT' | translate), type: 'number',
                           placeholder: ('PROFILES.PLACEHOLDERS.SALARY_RH' | translate) }"
              [value]="editForm().salaireNetRh ?? null"
              (valueChange)="patch.emit({ salaireNetRh: asNumber($event) })" />
            <rh-profile-field variant="row"
              [label]="'PROFILES.FIELDS.CURRENCY' | translate" [value]="CURRENCY" />
            <rh-profile-field variant="row" [last]="true"
              [label]="'PROFILES.FIELDS.PAY_FREQUENCY' | translate"
              [value]="'PROFILES.PAY_FREQUENCY.MONTHLY' | translate" />
          </div>
        }
      </rh-section-card>
    </div>

    <!-- Values the design's two cards don't carry, kept visible without changing
         their shape: contract end, onboarding state, and the audit stamps. -->
    @if (!editMode()) {
      <div class="mt-4 flex flex-wrap gap-x-6 gap-y-1 px-1 text-[11px] text-on-surface-variant">
        <span>
          {{ 'PROFILES.FIELDS.CONTRACT_END' | translate }}:
          <b class="font-semibold text-on-surface">{{ fmtDate(profile().contractEndDate) ?? '—' }}</b>
        </span>
        <span>
          {{ 'PROFILES.FIELDS.ONBOARDING' | translate }}:
          <b class="font-semibold" [class]="profile().onboardingCompleted ? 'text-teal' : 'text-warning'">
            {{ onboardingText() }}
          </b>
        </span>
        <span>
          {{ 'PROFILES.FIELDS.CREATED_AT' | translate }}:
          <b class="font-semibold text-on-surface">{{ fmtDate(profile().createdAt) ?? '—' }}</b>
        </span>
        <span>
          {{ 'PROFILES.FIELDS.UPDATED_AT' | translate }}:
          <b class="font-semibold text-on-surface">{{ fmtDate(profile().updatedAt) ?? '—' }}</b>
        </span>
      </div>
    }
  `,
})
export class EmploymentSectionComponent {
  private translate = inject(TranslateService);

  readonly profile  = input.required<EmployeeProfile>();
  readonly editMode = input(false);
  readonly editForm = input.required<ProfileUpdateDto>();

  readonly contractTypeOptions = input<SelectOption[]>([]);

  readonly patch = output<Partial<ProfileUpdateDto>>();

  /** Salaries are stored and displayed in TND — there is no currency column. */
  protected readonly CURRENCY = 'TND';

  protected readonly fmtDate  = fmtDate;
  protected readonly toDate   = toDate;
  protected readonly fromDate = fromDate;
  protected readonly asNumber = asNumber;

  /** Grouped integer part, TND suffix. `null` so the field renders its em dash. */
  protected amount(value: number | null | undefined): string | null {
    if (value == null) return null;
    return `${value.toLocaleString('fr-FR')} ${this.CURRENCY}`;
  }

  /** "Terminé · 12 mars 2024", or just the state when there is no completion date. */
  protected onboardingText(): string {
    this.translate.currentLang();
    const p = this.profile();
    const state = this.translate.instant(
      p.onboardingCompleted ? 'PROFILES.ONBOARDING.DONE' : 'PROFILES.ONBOARDING.PENDING',
    );
    const at = fmtDate(p.onboardingCompletedAt);
    return at ? `${state} · ${at}` : state;
  }
}
